service: sls-nest-9

useDotenv: true

# Plugin settings
plugins:
  - serverless-offline
  - serverless-deployment-bucket
provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  environment:
    ACCOUNT_ID: ${env:ACCOUNT_ID}
  deploymentBucket:
    name: ${self:service}-${aws:accountId}-${sls:stage}
    serverSideEncryption: AES256

custom:
  prune:
    automatic: true
    number: 3 # Save up to 3 versions

functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    layers:
      - { Ref: NodeLambdaLayer }

  # Single service execution
  hello:
    handler: dist/function/hello.handler
    events:
      - http:
          method: GET
          path: /hello
    layers:
      - { Ref: NodeLambdaLayer }

package:
  patterns:
    - '!node_modules/**'
    - '!layer/**'
    - '!src/**'
    - '!.yarn/**'
    - '!.serverless/**'
    - '!test/**'
    - '!.idea/**'

layers:
  node:
    path: layer/modules/node
    name: ${self:service}-${sls:stage}-nodeLayer
    description: Description of what the lambda layer does 
    compatibleRuntimes:
      - nodejs16.x
    package:
      patterns:
        - node_modules/**

#resources:
#  Resources:
#    DynamoDbUser:
#      Type: AWS::DynamoDB::Table
#      Properties:
#        AttributeDefinitions:
#          - AttributeName: id
#            AttributeType: S
#        KeySchema:
#          - AttributeName: id
#            KeyType: HASH
#        ProvisionedThroughput:
#          ReadCapacityUnits: 1
#          WriteCapacityUnits: 1
#        TableName: user-${sls:stage}